<a href="https://colab.research.google.com/github/SUSHWANTH1567/23CSBTB29/blob/main/ASSIGNMENT_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Implement basic data structures using numpy and pandas
1. Lists
2. Arrays
3. Identify their type using type()
4. Perform mathematical operations on these datasets created - multiplication, division,
poweroff
5. Combine text with Numpy fuction to generate a textual output - ”Addition of Two:
array1 +array 2
6. Implement np.sin(), log(), log2(), np.exp())

In [ ]:
lst={2:4,5:25,3:9,8:64,6:36}
print (lst)
print(type(lst))

{2: 4, 5: 25, 3: 9, 8: 64, 6: 36}
<class 'dict'>


In [ ]:
lst={12:24,11:22,13:26,14:28}
print (lst)
print(type(lst))

{12: 24, 11: 22, 13: 26, 14: 28}
<class 'dict'>


In [ ]:
lst={10:"apple",5:"banana",50:"dragon"}
print (lst)
print(type(lst))

{10: 'apple', 5: 'banana', 50: 'dragon'}
<class 'dict'>


In [ ]:

import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)
array1

array([1, 2, 3])

In [ ]:
import numpy as np
lst1=[1,2,3]
lst2=[2,5,7]
array1 = np.array(lst1)
array2=  np.array(lst2)
add=array1+array2
print(add)



[ 3  7 10]


In [ ]:
import numpy as np
lst1=[1,2,3]
lst2=[2,5,7]
array1 = np.array(lst1)
array2=  np.array(lst2)
mul=array1*array2
print(mul)



[ 2 10 21]


In [ ]:
import numpy as np
lst1=[1,2,3]
lst2=[2,5,7]
array1 = np.array(lst1)
array2=  np.array(lst2)
sub=array1-array2
print(sub)



[-1 -3 -4]


In [ ]:
import numpy as np
lst1=[1,2,3]
lst2=[2,5,7]
array1 = np.array(lst1)
array2=  np.array(lst2)
div=array1/array2
print(div)

[0.5        0.4        0.42857143]


In [ ]:
import numpy as np
lst1=[1,2,3]
lst2=[2,5,7]
array1 = np.array(lst1)
array2=  np.array(lst2)
power=array1**array2
print(power)



[   1   32 2187]


In [ ]:
array = np.array([2, 5, 7, 3, 8])
print("NumPy Array:", array)
print("Type:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])
print("Sum of elements:", np.sum(array))
print("Mean of elements:", np.mean(array))

NumPy Array: [2 5 7 3 8]
Type: <class 'numpy.ndarray'>
First element: 2
Last element: 8
Sum of elements: 25
Mean of elements: 5.0


In [ ]:
array = np.array([2, 5, 7, 3, 8])
print("Array:", array)
print("Type of array:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])

Array: [2 5 7 3 8]
Type of array: <class 'numpy.ndarray'>
First element: 2
Last element: 8


In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Type of 1D Array:", type(array_1d))
print("Sum of elements:", np.sum(array_1d))
print("Mean of elements:", np.mean(array_1d))


1D Array: [1 2 3 4 5]
Type of 1D Array: <class 'numpy.ndarray'>
Sum of elements: 15
Mean of elements: 3.0


In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)
print("Type of 2D Array:", type(array_2d))
print("Sum of elements in 2D array:", np.sum(array_2d))
print("Transpose of 2D array:\n", np.transpose(array_2d))


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of 2D Array: <class 'numpy.ndarray'>
Sum of elements in 2D array: 45
Transpose of 2D array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)
print("Type of 3D Array:", type(array_3d))
print("Sum of elements in 3D array:", np.sum(array_3d))
print("Shape of 3D array:", array_3d.shape)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Type of 3D Array: <class 'numpy.ndarray'>
Sum of elements in 3D array: 78
Shape of 3D array: (2, 2, 3)


In [ ]:
# Creating a 4D array
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                     [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("4D Array:\n", array_4d)
print("Type of 4D Array:", type(array_4d))
print("Sum of elements in 4D array:", np.sum(array_4d))
print("Shape of 4D array:", array_4d.shape)


4D Array:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Type of 4D Array: <class 'numpy.ndarray'>
Sum of elements in 4D array: 136
Shape of 4D array: (2, 2, 2, 2)
